### ISSUE TITLE
Remove old v2 requirements such as build packs, version stream etc

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/issues#10]

**Comment by rawlingsj** [comment]
todo list so we don't forget

- [ ] update to `jx gitops upgrade` to migrate users cluster jx-requirements.yml, e.g something like this https://github.com/jenkins-x/jx-api-migrate/blob/40a0a07e3e14194fc7bb75c8880cd8b4d21269d8/main.go#L31-L35

- [ ] test with terraform, existing requirements in the default namespace should continue to work

- [ ] update base cluster quickstart repos

**Comment by rawlingsj** [comment]
open PRs

https://github.com/jenkins-x/jx-verify/pull/62
https://github.com/jenkins-x/jx-admin/pull/127
https://github.com/jenkins-x/jx-secret/pull/145
https://github.com/jenkins-x/jx-gitops/pull/395
https://github.com/jenkins-x/jx-application/pull/58
https://github.com/jenkins-x/jx-preview/pull/142
https://github.com/jenkins-x/jx-promote/pull/158
https://github.com/jenkins-x/jx-pipeline/pull/132
https://github.com/jenkins-x/jx-pipelines-visualizer/pull/43

**Comment by rawlingsj** [comment]
done

**Comment by gazal-k** [comment]
did u miss one: https://github.com/jenkins-x/jx-pipelines-visualizer/pull/43 ?
