### ISSUE TITLE
jx3 - add option to trigger pipeline after app clusterrelease

### ISSUE THREAD

**Issue by peter-poki** [jenkins-x/issues#20]
Hello guys,

it would be nice to have option to trigger some pipeline after application was released to the environment, e.g. to trigger some automated tests, smoke tests, etc...

For some more info, see discussion here:
https://kubernetes.slack.com/archives/C9MBGQJRH/p1606988337465300

**Comment by jstrachan** [comment]
we've got a post install hook now for triggering arbitrary actions whenever a change has been made to an cluster/environment:
https://jenkins-x.io/v3/develop/faq/general/#how-do-i-add-a-post-install-hook-in-a-cluster
