### ISSUE TITLE
Restore the jx2 "merge and rebase" mechanisms

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x/issues#22]
See [Slack thread](https://kubernetes.slack.com/archives/C9MBGQJRH/p1606937640412000?thread_ts=1606933572.406500&cid=C9MBGQJRH)

> (...) if both projects were imported it’s probably just a case of fixing a merge conflict on the promote PR or retriggering. We used to rebase & combine promote PRs; we lost that on the migration to V3 but would be good to get back (at least the rebasing)

**Comment by jstrachan** [comment]
Promote PRs on environments should auto-rebase and merge now
