### ISSUE TITLE
jx3 - jx-release-version - add support for semantic-release

### ISSUE THREAD

**Issue by peter-poki** [jenkins-x/issues#23]
Can you please add functionality to the `jx-release-version` image to support `semantic-release`? By semantic release I mean, that it will analyze last commit message, and if it starts with `fix:` or `feat:` would change `minor` or `major` version:
fix: 1.3.5 -> 1.3.6
feat: 1.3.5 -> 1.4.0

Originaly jx2 had this functionality with flag `--semantic-release`, image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136, this is probably the original code: https://github.com/jenkins-x/jx/blob/master/pkg/semrel/semrel.go#L54 

Thank you

**Comment by jstrachan** [comment]
should be fixed now in the latest catalog
