### ISSUE TITLE
Not able to bring up jx3 in GKE

### ISSUE THREAD

**Issue by james-knott** [jenkins-x/issues#36]
jx-boot failing. Here is the output in the gist.

https://gist.github.com/james-knott/489e0229e28cb9447e187cb81a6429e2

I just rebuilt the cluster and it came up without errors in terraform. 

The template is missing the config folder. I found it and rebuilt the cluster and this error went away.

**Comment by james-knott** [comment]
Error from server (InternalError): error when creating "config-root/namespaces/jx/acme-jx/tls-dev-cloudgitops-io-p-certificate.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: no endpoints available for service "cert-manager-webhook"
make[1]: *** [versionStream/src/Makefile.mk:280: kubectl-apply] Error 1
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:240: regen-check] Error 1

**Comment by james-knott** [comment]
config-root is missing from the template generator.

**Comment by james-knott** [comment]
New Errors after I resolved the config-root error

jx-webhook                    jx                            ERROR                         no webhook registered for dev: failed to create webhook "https://hook-jx.dev.cloudgitops.io/hook" on repository 'james-knott/gkecluster': Not Found
                                                                                          no webhook registered for james-knott-gkecloud: failed to create webhook "https://hook-jx.dev.cloudgitops.io/hook" on repository 'james-knott/gkecloud': Not Found
                                                                                          no webhook registered for james-knott-mybasicnodeapp: failed to create webhook "https://hook-jx.dev.cloudgitops.io/hook" on repository 'james-knott/mybasicnodeapp': Not Found

**Comment by jstrachan** [comment]
the log `last commit was a merge pull request so not regenerating` looks like you manually merged a PR that had not properly regenerated I guess. Try do a dummy commit on the main branch and try gist the `jx admin log` to see what a full regeneration job looks like.

incidentally failing to generate webhooks is usually a sign that your bot git token doesn't have the karma to add webhooks (e.g. try making it an admin of the repos)
