### ISSUE TITLE
Windows 10 - can't install helm plugin

### ISSUE THREAD

**Issue by kwit75** [jenkins-x/issues#38]
>>>>jx admin plugins upgrade
checking we have the correct vault CLI version
Installing plugin helm version 3.5.3 for command jx helm from https://get.helm.sh/helm-v3.5.3-windows-amd64.zip into C:\Users\KWiT\.jx3\plugins\bin
error: failed to check vault binary: open C:\Users\KWiT\AppData\Local\Temp\helm307491007\helm.exe: The system cannot find the file specified.
ERROR: exit status 1

**Comment by jstrachan** [comment]
@kwit75 whats the output of `jx version`? wonder if you've got a recent image

**Comment by jstrachan** [comment]
I'm fairly sure this is now fixed; we've unit tests that verify we can install plugins on the jx repo now https://github.com/jenkins-x/jx/blob/main/.github/workflows/plugins-pr.yaml#L20-L28
