### ISSUE TITLE
Keep getting 403 for cluster repo

### ISSUE THREAD

**Issue by cicd-breqwatr** [jenkins-x/issues#45]
error: failed to create Pull Request on the cluster git repository: failed to create Pull Request on the development environment git repository https://github.com/ci/jx3-kubernetes-cluster.git: failed to create pull request in dir /tmp/jx-git-427827075: failed to push to branch pr-5e8dd612-b190-4fb3-af8e-ab4e55163200 from dir /tmp/jx-git-427827075: failed to push to the branch [pr-5e8dd612-b190-4fb3-af8e-ab4e55163200:pr-5e8dd612-b190-4fb3-af8e-ab4e55163200]: failed to run 'git push origin --force pr-5e8dd612-b190-4fb3-af8e-ab4e55163200:pr-5e8dd612-b190-4fb3-af8e-ab4e55163200' command in directory '/tmp/jx-git-427827075', output: 'remote: Permission to ci/jx3-kubernetes-cluster.git denied to ....
fatal: unable to access 'https://ci-...@github.com/ci/jx3-kubernetes-cluster.git/': The requested URL returned error: 403'

**Comment by jstrachan** [comment]
sounds like your git user and token are not a collaborator of the repository?
