### ISSUE TITLE
Some commands are unavailable

### ISSUE THREAD

**Issue by Chabouchakour** [jenkins-x/issues#48]
Installed jx via the documentation on linux. First of all, jx version --short doesn't work (only js version). In addition to that, while trying a lot of commands like jx boot I get failed to load plugin. Would appreciate the help, thank's.

**Comment by tomhobson** [comment]
Hey @Chabouchakour, looks like you might have stumbled into some jx v2 documentation. 

We no longer use jx boot, if you look at the v3 docs ( https://jenkins-x.io/v3/about/ ) they should guide you in the right direction!
